name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pack
        run: dotnet pack src/Skunked/Skunked.csproj  --configuration Release --include-symbols --include-source
      - name: Push
        run: dotnet nuget push src/Skunked/bin/Release/Skunked.1.0.4.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json