name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pack
        run: dotnet pack src/Skunked/Skunked.csproj
      - name: Push
        run: dotnet nuget push src/Skunked/bin/Debug/Skunked.1.0.3.nupkg --api-key oy2odyaeyf3f2umjddcqbebvxzbhdvgebdk234cfak7btu --source https://api.nuget.org/v3/index.json --configuration Release --include-symbols --include-source